services:

  asa0:
    extends:
      file: common.yml
      service: asa
    container_name: ${COMPOSE_PROJECT_NAME}_asa0
    ports:
      - "${ASA0_SERVER_PORT}:${ASA0_SERVER_PORT}/udp"
    environment:
      - "SERVER_MAP=${ASA0_SERVER_MAP}"
      - "SESSION_NAME=${ASA_SESSION_PREFIX}${ASA0_SESSION_NAME}"
      - "SERVER_PORT=${ASA0_SERVER_PORT}"
      - "DISCORD_WEBHOOK_URL=${ASA0_DISCORD_WEBHOOK_URL:-${ASA_DISCORD_WEBHOOK_URL}}"
    # --- As asa0 is a cluster master server, the following specific settings are required. ---
      - "CLUSTER_MASTER=true"
      - "CLUSTER_NODES=${ASA0_CLUSTER_NODES:-1}"
      - "AUTO_BACKUP_ENABLED=${ASA0_AUTO_BACKUP_ENABLED}"
      - "AUTO_BACKUP_CRON_EXPRESSION=${ASA0_AUTO_BACKUP_CRON_EXPRESSION}"
      - "AUTO_UPDATE_ENABLED=${ASA0_AUTO_UPDATE_ENABLED}"
      - "AUTO_UPDATE_CRON_EXPRESSION=${ASA0_AUTO_UPDATE_CRON_EXPRESSION}"
    volumes:
      - ${HOST_CLUSTER_DIR:-.}/backups:/var/backups

# 以下の asa1 から asa9 までのセクションは、マップ数に応じて自動的に compose.override.yml ファイルに追加されます。直接編集しないでください。
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# 
# asa<no>:
#   extends:
#     file: common.yml
#     service: asa
#   container_name: ${COMPOSE_PROJECT_NAME}_asa<no>
#   ports:
#     - "${ASA<no>_SERVER_PORT}:${ASA<no>_SERVER_PORT}/udp"
#   environment:
#     - "SERVER_MAP=${ASA<no>_SERVER_MAP}"
#     - "SESSION_NAME=${ASA_SESSION_PREFIX}${ASA<no>_SESSION_NAME}"
#     - "SERVER_PORT=${ASA<no>_SERVER_PORT}"
#     - "DISCORD_WEBHOOK_URL=${ASA<no>_DISCORD_WEBHOOK_URL:-${ASA_DISCORD_WEBHOOK_URL}}"
#     - "LOG_FILE=ShooterGame_asa<no>.log" # Avoid log file conflicts
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  asa_config:
    container_name: ${COMPOSE_PROJECT_NAME}_asa_config
    image: busybox
    init: true
    command: httpd -vfh /web
    volumes:
      - ${HOST_CLUSTER_DIR:-.}/web:/web:ro
